#!/usr/bin/env node
// Regenerates derived version carriers from package.json (the single
// source of truth). Run automatically at the start of `npm run build`;
// also runnable directly via `npm run sync:version`.
// Do not edit server/version.ts or server.json versions by hand.

import fs from "node:fs"
import path from "node:path"

const repoRoot = process.cwd()
const packageJsonPath = path.join(repoRoot, "package.json")
const serverVersionPath = path.join(repoRoot, "server", "version.ts")
const serverMetadataPath = path.join(repoRoot, "server.json")

export function syncVersionFromPackageJson() {
	const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"))
	const version = packageJson.version
	if (!version || typeof version !== "string") {
		throw new Error(`No string "version" found in ${packageJsonPath}`)
	}

	const serverVersionSource = `// Code generated by scripts/sync-version.mjs from package.json. Do not edit by hand.
export const projectVersion = "${version}"
`
	fs.writeFileSync(serverVersionPath, serverVersionSource)

	if (fs.existsSync(serverMetadataPath)) {
		const serverMetadata = JSON.parse(fs.readFileSync(serverMetadataPath, "utf8"))
		serverMetadata.version = version
		if (Array.isArray(serverMetadata.packages)) {
			for (const pkg of serverMetadata.packages) {
				if (pkg && typeof pkg === "object") {
					pkg.version = version
				}
			}
		}
		fs.writeFileSync(serverMetadataPath, `${JSON.stringify(serverMetadata, null, 2)}\n`)
	}

	return version
}

const invokedDirectly = process.argv[1] === new URL(import.meta.url).pathname
if (invokedDirectly) {
	const version = syncVersionFromPackageJson()
	console.log(`Synced derived version files to ${version}`)
}
